---
# handlers file for apache-role
    - name: start Apache
      service:
        name: httpd
        state: started

    - name: Restart Apache
      service:
        name: httpd
        state: restarted
